### PR TITLE
Adds `useSignTransaction` hook

### PR DESCRIPTION
**Pull request by obber**
This sits on top of #36, will need to view 2e1125adc4efd70795365dfcd678e8717b81a66d to see the change.

Here's the loom, the first demo in the video shows it working. The second part of the video needs investigation, I think it's something to do with the set up, but will need to confirm with Bin.

https://www.loom.com/share/6ea92ac25ecf47e892cf77ac63dd9ca7

### CODE REVIEW

**Comment by dborstelmann** [comment]
loom link I don’t see?

**Comment by obber** [comment]
@dborstelmann updated sorry

**Review by dborstelmann — APPROVED** [review]
fyi I couldn't get any audio out of the loom.  Only comment, should we add a decline transaction button or cancel button?

**Comment by obber** [comment]
> fyi I couldn't get any audio out of the loom. Only comment, should we add a decline transaction button or cancel button?

I like that idea.

**Pull request merged**
